area_square = lambda side: side * side
area_rectangle = lambda length, breadth: length * breadth
area_triangle = lambda base, height: 0.5 * base * height
side = float(input("Enter side of square: "))
print("Area of Square =", area_square(side))
length = float(input("Enter length of rectangle: "))
breadth = float(input("Enter breadth of rectangle: "))
print("Area of Rectangle =", area_rectangle(length, breadth))
base = float(input("Enter base of triangle: "))
height = float(input("Enter height of triangle: "))
print("Area of Triangle =", area_triangle(base, height))
